---
title: An R Markdown document converted from "/Users/ganslats/Project/TMF-School/TMF-School-Datenanalyse-Visualisierung/Notebooks/teil-1-demo-01-john-snow.ipynb"
output: html_document
---

# Teil 1, Demo 1: Cholera-Daten von John Snow

## Bibliotheken & Konfiguration

```{r}
packages <- c("leaflet", "readr", "tidyr", "ggplot2")
install.packages(setdiff(packages, rownames(installed.packages())))
lapply(packages, require, character.only = TRUE)

base_url <- "https://raw.githubusercontent.com/ganslats/TMF-School-Datenanalyse-Visualisierung/master/Rohdaten/john-snow/"
```

## Zeitverlauf Infektionen & Todesf채lle laden

```{r}
snow.dates.raw <- read_csv(paste(base_url, "snow.dates.csv", sep=""), 
                           col_names = c("index", "date", "attacks", "deaths"),
                           col_types = cols("i", col_date(format = "%Y-%m-%d"), "i", "i"),
                           skip = 1)
head(snow.dates.raw)
```

## Zeitverlauf plotten

```{r}
snow.dates.long <- snow.dates.raw %>% pivot_longer(!c(index, date), names_to="variable", values_to="n")
options(repr.plot.width = 10, repr.plot.height = 2.5)
ggplot(snow.dates.long) +
    geom_area(aes(x=date, y=n, fill=variable), alpha=0.5, position="identity") 
```

## Geovisualisierung

### Koordinaten der Todesf채lle laden

```{r}
snow.deaths.raw <- read_csv(paste(base_url, "cholera_deaths.csv", sep=""), 
                            col_names=c("index", "deaths", "lon", "lat"), 
                            col_types = cols("i","i","d","d"), 
                            skip=1)
head(snow.deaths.raw)
```

### Todesf채lle auf der Karte anzeigen

```{r}
leafletmap <- leaflet() %>%
    setView(-0.136722, 51.513578, zoom=16) %>%
    addProviderTiles(providers$OpenStreetMap.DE) %>%
    addCircleMarkers(
        data = snow.deaths.raw, ~lon, ~lat,
        radius = ~deaths * 2,
        color = "red",
        stroke = FALSE,
        fillOpacity = 0.5
    )
leafletmap
```

### Koordinaten der Wasserpumpen laden

```{r}
snow.pumps.raw <- read_csv(paste(base_url, "johnsnow_pumps.csv", sep=""), 
                           col_names=c("index", "lon", "lat"), 
                           col_types = cols("i","d","d"), 
                           skip=1)
head(snow.pumps.raw)
```

## Wasserpumpen auf der Karte anzeigen

```{r}
# Wasserpumpen als Marker auf der Karte erg채nzen
leafletmap <- leafletmap %>%
  addMarkers(data = snow.pumps.raw, ~lon, ~lat)

# Karte ausgeben
leafletmap
```
